# This workflow validates, deploys, and runs the specified bundles
# withina production target named "prod".
name: 'Production deployment'

# Ensure that only a single job or workflow using the same concurrency group #
#runs at a time .
concurrency: 1

# Trigger this workflow whwenever a pull request is pushed to the repo's
# mainn branch 
on: 
  push: 
    branches:
       - main
    paths:
       -  'databricks_analytics/**'

jobs:
    deploy:
      name:  'Deploy bundle'
      runs_on: ubuntu-latest


      steps:
      #check out this repo,so that this workflow can access it.
      -uses: actions/checkout@v3

      #Downlaod the Databricks Cli
      # see https://github.com/databricks/setup-cli
      -uses: databricks/setup-cli@main

      #Deploy the bundle to the "prod" target as defined
      #In the bundle's setting file.
      -run: databricks bundle deploy
      working-directory: databricks_analytics
      env:
         DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN}}
         DATABRICKS_BUNDLE_ENV: prod
      
      
      
      






    mnn
